config/routes.rb
Rails.application.routes.draw do

  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'users/:id/index', to: 'users#show', as: 'user_products'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :users
  resources :comments
  root to: 'products#index'
  put 'product/:id', to: 'products#bid'
  get 'product/:id', to: 'products#buy', as: 'buy'
  get 'product/:id', to: 'products#buy_by_time', as: 'buy_time'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products, dependent: :destroy
  attr_accessor :remember_token
  has_secure_password
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, case_sensitive: false}
  validates :firstname, length: {in: 2..15}
  validates :lastname, length: {in: 2..15}
  validates :password, confirmation: true, length: {in: 2..25 }, :on => :create
  validates :password, confirmation:false, :on => :update
  validates :password_confirmation, presence: true, :on => :create
  validates :password_confirmation, confirmation: false, :on  => :update

  ratyrate_rater
  ratyrate_rateable 'trustability'
  is_impressionable

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  impressionist :actions=>[:show]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @products = @user.products
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def change_admin
    @user = User.find(params[:id])
    @user.admin = "1";
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        redirect_back_or user
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
    end


  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user

      end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:id].nil?
        @user = "nill"
      else
        @user = User.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :postal_adress, :admin, :tag_list)
    end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user && (current_user?(@user) || current_user.admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>    <div class="field">
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
</div>
    <div>

    </div>
  <div class="field">
    <%= f.label :postal_adress %><br>
    <%= f.text_field :postal_adress %>
  </div>

    <% if current_user.admin == @user %>
        <%= f.label :admin %><br>
        <%= f.text_field :admin %>
        <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Postal adress</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.postal_adress %></td>
        <td><%= link_to 'Profile', user, class: "btn btn-info" %>
          <%= link_to 'Edit', edit_user_path(user) , class: "btn btn-info" if current_user == user || current_user.admin? %>
        <% if current_user == user || current_user.admin? %>
          <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info" %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New User', new_user_path, method: :get, :class => "btn btn-primary" %>

app/views/users/index_user_products.html.erb
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <td>Title</td>
    <td>Description</td>
    <td>Price</td>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <p>toto</p>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Postal adress:</strong>
  <%= @user.postal_adress %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<% if current_user %>
    Trustability: <%= rating_for @user, "trustability" %>
    <br>
<% end %>

<h1>Products created</h1>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <td>Title</td>
    <td>Description</td>
    <td>Price</td>
    <td>Actions</td>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <%= link_to 'Show', product_path, class: "btn btn-info" %>
          <%= link_to 'Edit', edit_product_path(product) , class: "btn btn-info" if current_user == @user || current_user.admin?%>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<br>

<h2>Products in bidding process</h2>


    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <td>Title</td>
        <td>Description</td>
        <td>Price</td>
      </tr>
      </thead>

      <tbody>
      <% @products.each do |product| %>
          <% if product.bidder_id != nil && product.buyer_id == nil %>
          <tr>
            <td><%= product.title %></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
            <% end %>
      <% end %>
          </tr>
      </tbody>
      </table>

<br>
<br>


<h2>Products sold</h2>


<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <td>Title</td>
    <td>Description</td>
    <td>Price</td>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <% if product.buyer_id != nil %>
          <tr>
            <td><%= product.title %></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
      <% end %>
  <% end %>
  </tr>
  </tbody>
</table>
<br>
<br>

<h1>Stats</h1>

<h2>Visits of your profile page : <%= @user.impressionist_count %></h2><br>

<h2>Visits per product</h2>

<table class="table table-bordered table-hover">
  <thead>
  <% @products.each do |product| %>
  <td><%= product.title %> </td>
  <% end %>
  </thead>
  <tbody>
  <% @products.each do |product| %>
      <td><%= product.impressionist_count %> </td>
  <% end %>
  </tbody>
</table>
<br>

<h2>Visits per category</h2>

<table class="table table-bordered table-hover">
  <thead>
      <%categories = Category.where('id in (?)', Product.select('distinct category_id').where('user_id = ?', @user.id)) %>
      <% categories.each do |cat| %>
      <td><%= cat.name %></td>
      <% end %>
  </thead>
  <tbody>
  <% categories.each do |cat| %>


  <% end %>
  </tbody>
</table>
<br>







<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>