config/routes.rb
Rails.application.routes.draw do

  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'users/:id/index', to: 'users#show', as: 'user_products'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :users
  resources :comments
  root to: 'products#index'
  put 'product/:id', to: 'products#bid'
  get 'product/:id', to: 'products#buy', as: 'buy'
  get 'product/:id', to: 'products#buy_by_time', as: 'buy_time'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_ancestry
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  autocomplete :category, :name
  impressionist :actions=>[:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    categories = @category.subtree
    @products = []
    categories.each do |cat|
     @products += cat.products
    end


  end

  # GET /categories/new
  def new
    @category = Category.new(:parent_id => params[:parent_id])
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <%= f.hidden_field :parent_id %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :parent_id %><br>
      <%= f.collection_select(:parent_id, Category.all, :id, :name, include_blank: 'None') %>
    </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Create sub-category', new_category_path(:parent_id => category.id) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category Name:</strong>
  <%= @category.name %>
</p>

<% @category.ancestors.each do |a| %>
 <%= link_to a.name, a %>
    &gt;
  <% end %>
<%= @category.name %>


<p>



<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <td>Title</td>
    <td>Category</td>
    <td>Description</td>
    <td>Price</td>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <% if  @category != product.category %>
        <td><%= link_to product.category.name, category_path(product.category) %></td>
            <% else %>
        <td><%=  product.category.name %></td>
            <% end %>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <%= link_to 'Show', product_path, class: "btn btn-info" %>
          <%= link_to 'Edit', edit_product_path(product) , class: "btn btn-info" if current_user == @user || current_user.admin?%>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>



<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>