config/routes.rb
Rails.application.routes.draw do

  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'users/:id/index', to: 'users#show', as: 'user_products'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :users
  resources :comments
  root to: 'products#index'
  put 'product/:id', to: 'products#bid'
  get 'product/:id', to: 'products#buy', as: 'buy'
  get 'product/:id', to: 'products#buy_by_time', as: 'buy_time'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  validates :user_id, presence: false
  default_scope -> {order(created_at: :desc)}
  validates :title, length: {in: 3..50 }
  validates :price, numericality: {greater_than: 0}
  validates :category_id, confirmation: true
  validates :description, allow_blank:true, length: {minimum: 2}
  ratyrate_rateable 'quality'
  acts_as_commentable
  is_impressionable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  impressionist :actions=>[:show]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :bid, :buy, :buy_time]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
      @product = Product.find(params[:id])
      if @product.buyer_id
        redirect_to root_path
      end

      @new_comment = Comment.build_from(@product, current_user.id, "")
    end


  def user_products
    @products = Product.where(:user_id, params[:user_id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def buy
    respond_to do |format|
      @product.buyer_id = current_user.id
      if @product.update(:buyer_id => @product.buyer_id)
        format.html { redirect_to @product, notice: 'Product was successfully buyed.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
    end

    def buy_by_time
      respond_to do |format|
        @product.buyer_id = @product.bidder_id
        if @product.update(:buyer_id => @product.buyer_id)
          format.html { redirect_to @product, notice: 'Product was successfully buyed.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end

  end

  def bid
    respond_to do |format|
      @product_tmp = product_params
      if @product.bidmax.nil? || @product.bidmax < @product_tmp["price"].to_i
        if @product.bidmax.nil?
          @bidmaxtmp = @product.price
        else
          @bidmaxtmp = @product.bidmax
        end
        @product.bidmax = @product_tmp["price"].to_i
        @product_tmp["price"] = @bidmaxtmp +=1
        @product.bidder_id = current_user.id
        if @product.update(@product_tmp)
          format.html { redirect_to @product, notice: 'bid accepted.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { redirect_to @product, notice: 'insufficient bid !' }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      else
        if @product_tmp["price"].to_i > @product.price
          @bidtmp = @product_tmp["price"].to_i
          @bidtmp += 1
          @product_tmp["price"] = @bidtmp
          if  @product.update(@product_tmp)
            format.html { redirect_to @product, notice: 'An other bidder have the best bid.' }
            format.json { render :show, status: :ok, location: @product }
          else
            format.html { redirect_to @product, notice: 'oh non !' }
            format.json { render json: @product.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to @product, notice: 'insufficient bid !' }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  end



  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)
    @product.price = @product.price_minimum
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      puts params[:action]
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :user_id, :category_id, :price_minimum, :mini_bid, :immediate_price, :bidder_id, :bidding_date_end, :bidmax, :buyer_id)
    end

  end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
      <%= f.label :price_minimum, "starting price" %><br>
      <%= f.text_field :price_minimum %>
    </div>
    <div class="field">
      <%= f.label :mini_bid, "reserving price" %><br>
      <%= f.text_field :mini_bid %>
    </div>
    <div class="field">
      <%= f.label :immediate_price, "immediate purchasing price" %><br>
      <%= f.text_field :immediate_price %>
    </div>
    <div class="field">
      <%= f.label :bidding_date_end, "end of bidding" %><br>
      <%= f.date_select :bidding_date_end %>
    </div>


  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>

    <p><%= link_to 'Create New Category', new_category_path %></p>
  <div class="actions">
    <%= f.submit %>
  </div>
    <% if current_user || current_user.admin? %>
        <%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info" %>
    <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <% if product.buyer_id == nil %>
      <tr>
        <td><%= link_to Category.find_by(id: product.category_id).name, category_path(Category.find_by(id: product.category_id)) %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <% if current_user.present? && (current_user == product.user || current_user.admin?) %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
      </tr>
    <% end %>
      <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Product', new_product_path, method: :get, :class => "btn btn-primary" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Remaining time:</strong>
  <% @t1 = @product.bidding_date_end
     @t2 = Time.now.to_datetime
     @duree = @t1 - @t2
     @heures=(@duree / 0.36).round / 10000
     @minutes=((@duree % 3600) / 0.006).round / 10000
     @secondes=(((@duree % 3600) % 60)*10000).round / 10000%>
  <%= @heures %> hours <%= @minutes %> minutes <%= @secondes %> secondes
</p>

<% if @duree == 0 %>

    <% controller.redirect_to buy_time_path(@product) ,method: :get %>

<% end %>


<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price :</strong>
  <%= @product.price %>€
</p>

<% if @product.price < @product.mini_bid %>
    <p>
      <strong>The minimum price is not reached</strong>
    </p>
    <% end %>

<% if @product.bidder_id == current_user.id %>
    <p>
      <strong>You are the best bidder</strong>
    </p>
<% end %>

<% if @product.price >= @product.immediate_price %>

  <% controller.redirect_to buy_path(@product) ,method: :get %>

     <% end %>

<% if current_user != @product.user %>

<p>
  <strong>Immediate purchase :</strong> <%= @product.immediate_price %> € <%= link_to 'Buy', buy_path(@product) ,method: :get %>
</p>
<p>

<%= form_for @product, :url => url_for(:controller => 'products', :action => 'bid'), method: :put do |f| %>
  <div>
    <%= f.text_field :price %>
  </div>
    <div>
      <%= f.submit "To bid", :class => "btn btn-success" %>
    </div>
<% end %>

<p>
  <strong>Category:</strong>
  <%= link_to Category.find_by(id: @product.category_id).name, category_path(Category.find_by(id: @product.category_id)) %>
</p>


<% if (@product.user_id != session[:user_id]) %>

<div class="row">
  <br>
  <div class="small-2 large-4 columns">
    <% if current_user %>
        Quality: <%= rating_for @product, "quality" %>
        <br>
    <% end %>
  </div>
</div>

    <% end %>

<%= render partial: "comments/template", locals: {commentable: @product, new_comment: @new_comment} %>

    <% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>