config/routes.rb
Rails.application.routes.draw do

  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'users/:id/index', to: 'users#show', as: 'user_products'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :users
  resources :comments
  root to: 'products#index'
  put 'product/:id', to: 'products#bid'
  get 'product/:id', to: 'products#buy', as: 'buy'
  get 'product/:id', to: 'products#buy_by_time', as: 'buy_time'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dragozone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if logged_in?  %>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Categories', categories_path %></li>
            <li class='dropdown'>
              <a href="#", class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li><%= link_to 'My products', products_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Log out', logout_path, method: 'delete' %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :id => key %>
<% end %>

<%= yield %>

</body>
</html>